# Generated by Django 4.0.3 on 2022-04-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_results_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='occupation',
            field=models.CharField(default='developer', max_length=200),
        ),
    ]
