# Generated by Django 4.0.3 on 2022-05-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_remove_results_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
