# Generated by Django 4.0.3 on 2022-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_student_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mail',
            field=models.CharField(max_length=100),
        ),
    ]
