# Generated by Django 4.0.3 on 2022-05-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_techstack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstack',
            options={'verbose_name_plural': 'Technologies'},
        ),
    ]
