# Generated by Django 4.0.3 on 2022-05-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_alter_techstack_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techstack',
            name='used',
        ),
    ]
