# Generated by Django 4.0.3 on 2022-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_remove_techstack_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='name',
            field=models.CharField(choices=[('python', 'python'), ('linux', 'linux'), ('java', 'java'), ('go', 'go'), ('mysql', 'mysql')], help_text='technology name', max_length=100),
        ),
    ]
