# Generated by Django 4.0.3 on 2022-05-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_number_of_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='stack',
            field=models.CharField(default='Python', max_length=150),
        ),
    ]
