# Generated by Django 4.0.3 on 2022-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='stack',
            field=models.CharField(default='python', max_length=150),
        ),
    ]
