# Generated by Django 4.0.3 on 2022-06-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assigned_to',
            field=models.CharField(choices=[('empty', 'empty'), ('development', 'development'), ('engineering', 'engineering')], default='', max_length=50),
        ),
    ]
