# Generated by Django 4.0.3 on 2022-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quiz_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='assigned_to',
            field=models.CharField(choices=[('empty', 'empty'), ('development', 'development'), ('engineering', 'engineering')], default='empty', max_length=50),
        ),
    ]
