# Generated by Django 4.0.3 on 2022-07-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_alter_quiz_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='set true if the quiz is mandatory for everybody'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='assigned_to',
            field=models.CharField(choices=[('all', 'all'), ('development', 'development'), ('engineering', 'engineering')], default='all', max_length=50),
        ),
    ]
