# Generated by Django 4.0.3 on 2022-07-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quiz_is_mandatory_alter_quiz_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='stack',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
