# Generated by Django 4.0.3 on 2022-07-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_quiz_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_mandatory',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='stack',
            field=models.CharField(default='common', max_length=150),
        ),
    ]
